version: "3"
services:
    nginx:
        image: nginx:stable-alpine
        ports: 
            - "3000:80"
        volumes: 
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf

    node-app:
        build: .
        env_file: 
            - ./.env
        depends_on: 
            - mongo
        
    mongo:
        image: mongo
        env_file: 
            - ./.env
        volumes: 
            - mongo-db:/data/db

volumes: 
    mongo-db: