version: "3"
services:
    node-app:
        build: .
        ports: 
            - "3000:3000"
        volumes: 
            - ./:/app
            - /app/node_modules
        env_file: 
            - ./.env